"""Abstract store protocol for ANPEGT-POL."""

from typing import Optional, Protocol

from anpegt.schema.anp import PrioritySnapshot
from anpegt.schema.corpus import ChunkRecord, CorpusDocument
from anpegt.schema.cycle import CycleRun
from anpegt.schema.fitness import FitnessScore
from anpegt.schema.plan import CommunicationPlan, GlobalPlan, SectorPlan, SocialPost, Speech
from anpegt.schema.voter import SegmentEmbedding


class Store(Protocol):
    """Protocol defining the persistence interface for ANPEGT-POL."""

    def save_cycle_run(self, run: CycleRun) -> None: ...

    def get_cycle_run(self, cycle_number: int) -> Optional[CycleRun]: ...

    def get_latest_cycle_run(self) -> Optional[CycleRun]: ...

    def save_priority_snapshot(self, snap: PrioritySnapshot) -> None: ...

    def get_priority_snapshot(self, cycle_id: str) -> Optional[PrioritySnapshot]: ...

    def save_sector_plan(self, plan: SectorPlan) -> None: ...

    def get_sector_plans(self, cycle_id: str) -> list[SectorPlan]: ...

    def save_global_plan(self, plan: GlobalPlan) -> None: ...

    def get_global_plan(self, cycle_id: str) -> Optional[GlobalPlan]: ...

    def save_communication_plan(self, plan: CommunicationPlan) -> None: ...

    def get_communication_plans(self, cycle_id: str) -> list[CommunicationPlan]: ...

    def save_social_post(self, post: SocialPost) -> None: ...

    def get_social_posts(self, cycle_id: str) -> list[SocialPost]: ...

    def save_speech(self, speech: Speech) -> None: ...

    def get_speeches(self, cycle_id: str) -> list[Speech]: ...

    def save_fitness_score(self, score: FitnessScore) -> None: ...

    def get_fitness_scores(self, cycle_id: str) -> list[FitnessScore]: ...

    def save_segment_embedding(self, emb: SegmentEmbedding) -> None: ...

    def get_latest_segment_embedding(self, segment_id: str) -> Optional[SegmentEmbedding]: ...

    def save_corpus_document(self, doc: CorpusDocument) -> None: ...

    def save_chunk_record(self, chunk: ChunkRecord) -> None: ...

    def get_chunks_by_cluster(self, cluster_id: str, limit: int = 10) -> list[ChunkRecord]: ...

    def get_cycle_history(self, last_n: int = 10) -> list[CycleRun]: ...
